config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/mentions', to: 'users#mentions', as: 'mentions'
  get '/timeline', to: 'users#timeline', as: 'timeline'
  get '/hashtags/:id', to: 'hashtags#show'
  get '/:username' => 'users#show', as: 'user'

  resources :users, only: [:new, :create] do
    member do
      get 'follow'
      get 'unfollow'
    end
  end
  resources :statuses, only: [:new, :create]

end

app/models/mention.rb
class Mention < ActiveRecord::Base
  belongs_to :users, class_name: 'User', foreign_key: 'mention_id'
  belongs_to :status
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :followers, class_name: 'User', foreign_key: 'follower_id'
  belongs_to :leaders, class_name: 'User', foreign_key: 'leader_id'
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :creator, class_name: 'User'

  validates :body, presence: true
  validates :creator, presence: true

  after_save :extract_mentions

  def extract_mentions
    mentions = self.body.scan(/@(\w*)/).flatten
    mentions.each do |name| 
       user = User.find_by(username: name)
       Mention.create(mention_id: user.id, status_id: self.id) if user
    end if mentions
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :statuses, foreign_key: 'creator_id'
  has_many :mentions, foreign_key: 'mention_id'
  has_many :num_of_unseen_mentions, -> { where viewed_at: nil}, foreign_key: 'mention_id', class_name: "Mention"

  has_many :follower_relationships, class_name: "Relationship", foreign_key: "leader_id"
  has_many :leader_relationships, class_name: "Relationship", foreign_key: "follower_id"

  has_many :followers, through: :follower_relationships , source: :followers
  has_many :leaders, through: :leader_relationships , source: :leaders

  validates :username, presence: true

  # def num_of_unseen_mentions
  #   self.mentions.where(viewed_at: nil).count
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    redirect_to root_path if !logged_in?
  end

end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController

  def show
    @statuses = Status.where("body LIKE ?", "%#{params[:id]}%")
    @header = params[:id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = "Successfully logged in!"
      redirect_to user_path(@user.username)
    else
      flash[:warning] = "There was a problem, please try again."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  def new
    @status = Status.new
  end

  def create
    @status = Status.new(status_params)
    @status.creator_id = session[:user_id]

    if @status.save
      flash[:notice] = "Status tweeted!"
      redirect_to user_path(@status.creator.username)
    else
      render 'new'
    end
  end

  private

  def status_params
    params.require(:status).permit(:body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:follow]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "#{@user.username} user created!"
      redirect_to user_path(@user.username)
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by(username: params[:username])
  end

  def follow
    user = User.find(params[:id])
    if user
      if current_user != user && !current_user.leaders.include?(user)
        current_user.leaders << user
        redirect_to user_path(user.username)
      else
        flash[:warning] = "An error occured"
        redirect_to user_path(current_user.username)
      end
    end
  end

  def mentions
    @mentions = current_user.mentions
    current_user.mentions.where(viewed_at: nil).update_all(viewed_at: Time.now)
  end

  def unfollow
    user = User.find(params[:id])
    current_user.leaders.delete(user)
    redirect_to user_path(user.username)
  end

  def timeline
    @statuses = []
    current_user.leaders.each do |leader|
      @statuses << leader.statuses.order(created_at: :desc)
    end if current_user.leaders.any?
    @statuses.flatten!
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def auto_link(str)
    str = str.gsub(/#(\w+)/, '<a href="/hashtags/\\1">#\1</a>').html_safe
    str = str.gsub(/@(\w+)/, '<a href="\1">@\1</a>')
    str.html_safe
  end

end

app/views/hashtags/show.html.erb
<%= render 'shared/header', header: @header %>
<%= render 'shared/status', statuses: @statuses %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/navbar' %>
<%= render 'shared/flash_messages' %>
<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<div class='alert alert-warning'>
<% obj.errors.full_messages.each do |error_msg| %>
<%= error_msg.to_s %>
<% end if obj.errors.any? %>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.keys.each do |key| %>
  <div class='alert alert-<%= key.to_s %>' role="alert">  <%= flash[key] %> </div>
<% end if flash.keys.any? %>

app/views/shared/_header.html.erb
<h4><%= header %></h4>
<hr>

app/views/shared/_navbar.html.erb
<% if logged_in? %>
<%= link_to 'New Tweet | ', new_status_path %>
<%= link_to 'Logout | ', logout_path %>
<%= link_to 'Timeline |', timeline_path %>
<%= link_to "Mentions (#{current_user.num_of_unseen_mentions.size})", mentions_path %>
<% else %>
<%= link_to 'Register | ', new_user_path %>
<%= link_to 'Login', login_path %>
<% end %>

app/views/shared/_status.html.erb
<ul>
<% statuses.each do |status| %>
  <li> <%= auto_link(status.body) %> by <%= status.creator.username %> </li>
<% end if statuses %>
</ul>

app/views/statuses/new.html.erb
<%= render 'shared/errors', obj: @status %>

<% if logged_in? %>
  <%= form_for @status do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br>
  <%= f.submit "Tweet!" %>
  <% end %>
<% end %>

app/views/users/index.html.erb
<%= render 'shared/header', header: "All Users" %>
<% @users.each do |user| %>
<%= link_to user.username, user_path(user.username) %>
<br>
<% end %>

app/views/users/mentions.html.erb
<%= render 'shared/header', header: "Mentions"%>

<ul>
<% @mentions.each do |mention| %>
  <li> <%= mention.status.body %> by <%= mention.status.creator.username %> </li>
<% end %>
</ul>

app/views/users/new.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.submit "Register!" %> 
<% end %>

app/views/users/show.html.erb
<%= render 'shared/header', header:  @user.username  %>

<% if logged_in? && current_user != @user %>
  <% if !current_user.leaders.include?(@user) %>
    <%= link_to "+ follow", follow_user_path(@user) %>
  <% else %>
    <%= link_to "unfollow", unfollow_user_path(@user) %>
  <% end %>
<% end %>

<br>

<%= render 'shared/status', statuses: @user.statuses %>

app/views/users/timeline.html.erb
<%= render 'shared/header', header: "Your timeline" %>

<ul>
<%= render 'shared/status', statuses: @statuses %>
</ul>